spring.application.name=demo

# dev-tools
spring.devtools.restart.enabled=true

# database (??????)
spring.datasource.type=com.alibaba.druid.pool.DruidDataSource
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

# JWT (????????? JwtUtils ?)
jwt.secret=${JWT_SECRET}
jwt.expiration=${JWT_EXPIRATION}

# MyBatis Plus Log
mybatis-plus.configuration.log-impl=org.apache.ibatis.logging.stdout.StdOutImpl